env:
  GITHUB_TOKEN:

linux_x68_64_task:
  container:
    image: rust:alpine
  registry_cache:
    folder: $CARGO_HOME/registry
    reupload_on_changes: true
    fingerprint_script: date +%Y
  target_cache:
    folder: target
    reupload_on_changes: true
    fingerprint_script:
      - echo $CIRRUS_OS
      - rustc --version
  setup_script:
    - apk add --no-cache curl libc-dev
  build_script:
    - cargo build --verbose --release
    - mv target/release/run-command-on-aws-lambda run-command-on-aws-lambda.$CIRRUS_OS.x86_64
    - ldd run-command-on-aws-lambda.$CIRRUS_OS.x86_64 || echo yay - statically linked
  binary_artifacts:
    path: run-command-on-aws-lambda.$CIRRUS_OS.*
  release_script: ./upload-binary.sh run-command-on-aws-lambda.$CIRRUS_OS.*
  before_cache_script: rm -f target/.rustc_info.json

linux_arm_task:
  arm_container:
    image: rust:alpine
  registry_cache:
    folder: $CARGO_HOME/registry
    reupload_on_changes: true
    fingerprint_script: date +%Y
  target_cache:
    folder: target
    reupload_on_changes: true
    fingerprint_script:
      - echo $CIRRUS_OS
      - rustc --version
  setup_script:
    - apk add --no-cache curl libc-dev
  build_script:
    - cargo build --verbose --release
    - mv target/release/run-command-on-aws-lambda run-command-on-aws-lambda.$CIRRUS_OS.aarch64
    - ldd run-command-on-aws-lambda.$CIRRUS_OS.aarch64 || echo yay - statically linked
  binary_artifacts:
    path: run-command-on-aws-lambda.$CIRRUS_OS.*
  release_script: ./upload-binary.sh run-command-on-aws-lambda.$CIRRUS_OS.*
  before_cache_script: rm -f target/.rustc_info.json
